name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask plotly

      - name: Generate static dashboard
        run: |
          cd dashboard-python
          python -c "
          import os
          import sys
          sys.path.append('.')
          from app import app, db_manager
          
          # Inicializar dados
          db_manager.inserir_modulos_iniciais()
          
          # Gerar HTML estático
          with app.test_client() as client:
              response = client.get('/')
              with open('../index.html', 'w', encoding='utf-8') as f:
                  f.write(response.get_data(as_text=True))
          
          print('Dashboard estático gerado com sucesso!')
          "

      - name: Create simple index if generation fails
        run: |
          if [ ! -f index.html ]; then
            cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Dashboard Galapagos DTVM</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
              <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
              <style>
                  body {
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                  }
                  .main-container {
                      background: white;
                      border-radius: 20px;
                      box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                      margin: 20px;
                      overflow: hidden;
                  }
                  .header {
                      background: linear-gradient(135deg, #2c3e50 0%, #3498db 100%);
                      color: white;
                      padding: 30px;
                      text-align: center;
                  }
                  .content {
                      padding: 40px;
                      text-align: center;
                  }
                  .btn-custom {
                      padding: 15px 25px;
                      border-radius: 10px;
                      font-weight: bold;
                      margin: 10px;
                      transition: all 0.3s ease;
                  }
                  .btn-custom:hover {
                      transform: translateY(-3px);
                      box-shadow: 0 10px 20px rgba(0,0,0,0.2);
                  }
              </style>
          </head>
          <body>
              <div class="main-container">
                  <div class="header">
                      <h1><i class="fas fa-map"></i> Mapa de Conciliações</h1>
                      <p>Galapagos DTVM - Sistema de Monitoramento</p>
                  </div>
                  
                  <div class="content">
                      <div class="alert alert-info">
                          <i class="fas fa-info-circle"></i>
                          <strong>Dashboard em Desenvolvimento</strong><br>
                          O sistema está sendo configurado. Use as opções abaixo para acessar.
                      </div>
                      
                      <h3><i class="fas fa-rocket"></i> Como Acessar o Dashboard</h3>
                      
                      <div class="row mt-4">
                          <div class="col-md-6">
                              <div class="card h-100">
                                  <div class="card-body">
                                      <h5><i class="fas fa-download"></i> Execução Local</h5>
                                      <p>Baixe o repositório e execute localmente:</p>
                                      <code>python executar_dashboard.py</code>
                                      <br><br>
                                      <a href="https://github.com/LeonardoMedicis/Galapagos-capital" class="btn btn-primary btn-custom">
                                          <i class="fab fa-github"></i> Ir para GitHub
                                      </a>
                                  </div>
                              </div>
                          </div>
                          
                          <div class="col-md-6">
                              <div class="card h-100">
                                  <div class="card-body">
                                      <h5><i class="fas fa-file-code"></i> Dashboard Simples</h5>
                                      <p>Versão HTML simples sem dependências:</p>
                                      <br>
                                      <a href="./dashboard_simples.html" class="btn btn-success btn-custom">
                                          <i class="fas fa-external-link-alt"></i> Abrir Dashboard
                                      </a>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="mt-5">
                          <h4><i class="fas fa-cogs"></i> Módulos de Conciliação</h4>
                          <div class="row">
                              <div class="col-md-4">
                                  <div class="card">
                                      <div class="card-header bg-success text-white">
                                          <i class="fas fa-chart-line"></i> Rentabilidade
                                      </div>
                                      <div class="card-body">
                                          <ul class="list-unstyled">
                                              <li>📈 Carteira A</li>
                                              <li>📈 Carteira B</li>
                                              <li>📈 Consolidada</li>
                                          </ul>
                                      </div>
                                  </div>
                              </div>
                              
                              <div class="col-md-4">
                                  <div class="card">
                                      <div class="card-header bg-danger text-white">
                                          <i class="fas fa-money-bill"></i> Impostos
                                      </div>
                                      <div class="card-body">
                                          <ul class="list-unstyled">
                                              <li>💰 IR Retido na Fonte</li>
                                              <li>💰 IOF Operações</li>
                                              <li>💰 PIS/COFINS</li>
                                          </ul>
                                      </div>
                                  </div>
                              </div>
                              
                              <div class="col-md-4">
                                  <div class="card">
                                      <div class="card-header bg-warning text-white">
                                          <i class="fas fa-cogs"></i> Operacionais
                                      </div>
                                      <div class="card-body">
                                          <ul class="list-unstyled">
                                              <li>🔧 Custódia Títulos</li>
                                              <li>🔧 Liquidação D+0</li>
                                              <li>🔧 Fechamento Dia</li>
                                          </ul>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  
                  <div class="bg-dark text-white text-center p-3">
                      <p>&copy; 2025 Galapagos DTVM - Sistema de Conciliações</p>
                      <p><small>Última atualização: $(date)</small></p>
                  </div>
              </div>
              
              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
          EOF
          fi

      - name: Copy additional files
        run: |
          # Copiar dashboard simples se existir
          if [ -f dashboard_simples.html ]; then
            cp dashboard_simples.html .
          fi
          
          # Copiar arquivos de documentação
          if [ -f DASHBOARD_PYTHON.md ]; then
            cp DASHBOARD_PYTHON.md .
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

